src/Entity/Teams.php
<?php

namespace App\Entity;

use App\Repository\TeamsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamsRepository::class)]
class Teams
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 132)]
    private ?string $name = null;

    #[ORM\Column(length: 32)]
    private ?string $country = null;

    #[ORM\Column(length: 16)]
    private ?string $money_balance = null;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Players", inversedBy="teams")
     * @ORM\JoinColumn(nullable=false)
     */
    private $player;

    // ...

    public function getPlayer(): ?Players
    {
        return $this->player;
    }

    public function setPlayer(Players $player): self
    {
        $this->player = $player;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getMoneyBalance(): ?string
    {
        return $this->money_balance;
    }

    public function setMoneyBalance(string $money_balance): self
    {
        $this->money_balance = $money_balance;

        return $this;
    }
}

src/Form/TeamsType.php
<?php

namespace App\Form;

use App\Entity\Teams;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TeamsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('country')
            ->add('money_balance')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Teams::class,
        ]);
    }
}

src/Controller/TeamsController.php
<?php

namespace App\Controller;

use App\Entity\Teams;
use App\Form\TeamsType;
use App\Repository\TeamsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/teams')]
class TeamsController extends AbstractController
{
    #[Route('/', name: 'app_teams_index', methods: ['GET'])]
    public function index(TeamsRepository $teamsRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $pagination = $paginator->paginate(
            $teamsRepository->findAll(),
            $request->query->getInt('page', 1), // page number
            2 // items per page
        );
        return $this->render('teams/index.html.twig', [
            'teams' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_teams_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TeamsRepository $teamsRepository): Response
    {
        $team = new Teams();
        $form = $this->createForm(TeamsType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $teamsRepository->save($team, true);

            return $this->redirectToRoute('app_teams_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('teams/new.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_teams_show', methods: ['GET'])]
    public function show(Teams $team): Response
    {
        return $this->render('teams/show.html.twig', [
            'team' => $team,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_teams_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Teams $team, TeamsRepository $teamsRepository): Response
    {
        $form = $this->createForm(TeamsType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $teamsRepository->save($team, true);

            return $this->redirectToRoute('app_teams_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('teams/edit.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_teams_delete', methods: ['POST'])]
    public function delete(Request $request, Teams $team, TeamsRepository $teamsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$team->getId(), $request->request->get('_token'))) {
            $teamsRepository->remove($team, true);
        }

        return $this->redirectToRoute('app_teams_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/teams/_delete_form.html.twig
<form method="post" action="{{ path('app_teams_delete', {'id': team.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ team.id) }}">
    <button class="btn">Delete</button>
</form>

templates/teams/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/teams/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Teams{% endblock %}

{% block body %}
    <h1>Edit Teams</h1>

    {{ include('teams/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_teams_index') }}">back to list</a>

    {{ include('teams/_delete_form.html.twig') }}
{% endblock %}

templates/teams/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Teams index{% endblock %}

{% block body %}
    <h1>Teams index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Country</th>
                <th>Money_balance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for team in teams %}
            <tr>
                <td>{{ team.id }}</td>
                <td>{{ team.name }}</td>
                <td>{{ team.country }}</td>
                <td>{{ team.moneyBalance }}</td>
                <td>
                    <a href="{{ path('app_teams_show', {'id': team.id}) }}">show</a>
                    <a href="{{ path('app_teams_edit', {'id': team.id}) }}">edit</a>
					<a href="{{ path('app_players_index', {'team_id': team.id}) }}">players</a>
					<a href="{{ path('app_purchase_players_index',{'team_id':team.id}) }}">Purchase Player From other Team</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
	<div class="pagination">
		{{ knp_pagination_render(teams) }}
	</div>
    <a href="{{ path('app_teams_new') }}">Create new</a> <br/>
	
{% endblock %}

templates/teams/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Teams{% endblock %}

{% block body %}
    <h1>Create new Teams</h1>

    {{ include('teams/_form.html.twig') }}

    <a href="{{ path('app_teams_index') }}">back to list</a>
{% endblock %}

templates/teams/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Teams{% endblock %}

{% block body %}
    <h1>Teams</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ team.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ team.name }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ team.country }}</td>
            </tr>
            <tr>
                <th>Money_balance</th>
                <td>{{ team.moneyBalance }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_teams_index') }}">back to list</a>

    <a href="{{ path('app_teams_edit', {'id': team.id}) }}">edit</a>

    {{ include('teams/_delete_form.html.twig') }}
{% endblock %}