src/Entity/Players.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\PlayersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayersRepository::class)]
class Players
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 132)]
    private ?string $name = null;

    #[ORM\Column(length: 32)]
    private ?string $surname = null;

    #[ORM\Column]
    private ?int $team_id = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $purchase_amount = null;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Teams", mappedBy="players")
     */
    private $team;

    // ...

    public function getTeam(): ?Teams
    {
        return $this->team;
    }

    public function setTeam(Teams $team): self
    {
        $this->team = $team;
        $team->setPlayer($this);

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getTeamId(): ?int
    {
        return $this->team_id;
    }

    public function setTeamId(int $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getPurchaseAmount(): ?string
    {
        return $this->purchase_amount;
    }

    public function setPurchaseAmount(?string $purchase_amount): self
    {
        $this->purchase_amount = $purchase_amount;

        return $this;
    }
}

src/Form/PlayersType.php
<?php

namespace App\Form;

use App\Entity\Players;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class PlayersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
		// dd($options['params']);
        $builder
            ->add('name')
            ->add('surname')
            ->add('team_id', HiddenType::class)
            ->add('purchase_amount')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Players::class,
        ]);
    }
}

src/Controller/PlayersController.php
<?php

namespace App\Controller;

use App\Entity\Players;
use App\Form\PlayersType;
use App\Repository\PlayersRepository;
use App\Repository\TeamsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/players')]
class PlayersController extends AbstractController
{
    #[Route('/{team_id}', name: 'app_players_index', methods: ['GET'])]
    public function index($team_id, PlayersRepository $playersRepository, PaginatorInterface $paginator, Request $request, TeamsRepository $teamRepository): Response
    {
        $players = $playersRepository->findBy(
            ['team_id' => $team_id]
        );
        foreach($players as $player) {

            $team = $teamRepository->find($player->getTeamId());
            $player->setTeam($team);
        }
        // dd($players);
        $pagination = $paginator->paginate(
            $players,
            $request->query->getInt('page', 1), // page number
            2 // items per page
        );
        return $this->render('players/index.html.twig', [
            'players' => $pagination,
            'team_id' => $team_id
        ]);

    }

    #[Route('/{team_id}/new', name: 'app_players_new', methods: ['GET', 'POST'])]
    public function new($team_id, Request $request, PlayersRepository $playersRepository): Response
    {
        // dd(123);
        $player = new Players();
        $player->setTeamId($team_id);
        $form = $this->createForm(PlayersType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playersRepository->save($player, true);

            return $this->redirectToRoute('app_players_index', ['team_id'=>$team_id], Response::HTTP_SEE_OTHER);
        }
        // dd($team_id);
        return $this->renderForm('players/new.html.twig', [
            'player' => $player,
            'form' => $form,
            'team_id' => $team_id
        ]);
    }

    #[Route('/{team_id}/{id}', name: 'app_players_show', methods: ['GET'])]
    public function show($team_id, Players $player): Response
    {
        return $this->render('players/show.html.twig', [
            'player' => $player,
            'team_id' => $team_id
        ]);
    }

    #[Route('/{team_id}/{id}/edit', name: 'app_players_edit', methods: ['GET', 'POST'])]
    public function edit($team_id, Request $request, Players $player, PlayersRepository $playersRepository): Response
    {
        $form = $this->createForm(PlayersType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playersRepository->save($player, true);

            return $this->redirectToRoute('app_players_index', ['team_id'=>$team_id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('players/edit.html.twig', [
            'player' => $player,
            'form' => $form,
            'team_id' => $team_id
        ]);
    }

    #[Route('/{team_id}/{id}', name: 'app_players_delete', methods: ['POST'])]
    public function delete($team_id, Request $request, Players $player, PlayersRepository $playersRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->request->get('_token'))) {
            $playersRepository->remove($player, true);
        }

        return $this->redirectToRoute('app_players_index', ['team_id'=>$team_id], Response::HTTP_SEE_OTHER);
    }
}

templates/players/_delete_form.html.twig
<form method="post" action="{{ path('app_players_delete', {'team_id': team_id,'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn">Delete</button>
</form>

templates/players/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/players/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Players{% endblock %}

{% block body %}
    <h1>Edit Players</h1>

    {{ include('players/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_players_index', {'team_id': team_id}) }}">back to list</a>

    {{ include('players/_delete_form.html.twig') }}
{% endblock %}

templates/players/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Players{% endblock %}

{% block body %}
    <h1>Players</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Team</th>
                <th>Purchased amount</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td>{{ player.id }}</td>
                <td>{{ player.name }}</td>
                <td>{{ player.surname }}</td>
                <td>{{ player.team.name }}</td>
                <td>{{ player.purchaseAmount }}</td>
                <td>
                    <a href="{{ path('app_players_edit', {'team_id': team_id,'id': player.id}) }}">Edit</a>
                    <a href="{{ path('app_players_show', {'team_id': team_id,'id': player.id}) }}">Delete</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
	<div class="pagination">
		{{ knp_pagination_render(players) }}
	</div>
    <a href="{{ path('app_players_new', {'team_id': team_id})}}">Create new</a> <br/>
	<a href="{{ path('app_teams_index') }}">Back to Teams</a>
{% endblock %}

templates/players/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Players{% endblock %}

{% block body %}
    <h1>Create new Players</h1>

    {{ include('players/_form.html.twig') }}

    <a href="{{ path('app_players_index', {'team_id': team_id}) }}">back to list</a>
{% endblock %}

templates/players/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Players{% endblock %}

{% block body %}
    <h1>Players</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ player.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ player.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ player.surname }}</td>
            </tr>
            <tr>
                <th>Team_id</th>
                <td>{{ player.teamId }}</td>
            </tr>
            <tr>
                <th>Purchase_amount</th>
                <td>{{ player.purchaseAmount }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_players_index',{'team_id': team_id}) }}">back to list</a>

    <a href="{{ path('app_players_edit', {'team_id': team_id,'id': player.id}) }}">edit</a>

    {{ include('players/_delete_form.html.twig') }}
{% endblock %}